### PR TITLE
Add PrestaShop Paylater with PayPlug & Oney banner on Payment page

### PR DESCRIPTION
**Pull request by Matt75**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | This is part of contractual engagement of PrestaShop Corp with PayPlug & Oney : display a promotional banner on BO > Improve > Payment > Payment Methods
| Type?         | new feature
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://forge.prestashop.com/browse/PAYSHIP-1544
| How to test?  | See below

⚠️ This is part of contractual engagement of PrestaShop Corp with PayPlug & Oney ⚠️

**How to test**

1. Go to BO > Modules > Module Manager
2. Install or Upgrade Gamification module
3. Go to BO > Improve > International > Localization
4. Set Default country to France or Italy
5. Go to BO > Improve > Payment > Payment Methods
6. If PrestaShop Checkout is already installed and fully onboarded, you should see this promotional block

**EN**
Capture d’écran 2022-05-13 à 11 10 16

**IT**
Capture d’écran 2022-05-13 à 12 41 39

**FR**
Capture d’écran 2022-05-13 à 12 41 22

### CODE REVIEW

**Review by seiwan — APPROVED** [review]

**Review by seiwan — APPROVED** [review]

**Review by seiwan — APPROVED** [review]

**Review by marwachelly — COMMENTED** [review]
Hello @Matt75,

I teste the PR following the steps above with PS17.7.8  and PS1.7.8.6. The promotional block is well added with italien english and french Employee language. But I detected a prooblem when trying to reset/ unistal / disable the module Gamification. Without PR (with the version from the branch dev ) the poblem doesn't exist.

**With PS1.7.7.8**

https://user-images.githubusercontent.com/89604350/169348170-b3c606ce-7abd-4928-832a-5f65e9373b48.mp4

**With PR PS1.7.8.6**

https://user-images.githubusercontent.com/89604350/169348236-0266a78a-8efe-4ce9-8b25-1c1b17e130ee.mp4

**Without PR PS1.7.8.5**

https://user-images.githubusercontent.com/89604350/169348259-2c0b8213-cc41-4d63-8b86-d4bad96cf67d.mp4

Could you please check?

Thanks,

**Comment by Matt75** [comment]
@marwachelly Hello 😃

Thanks for your work, your issue on reset / uninstall / disable is not a regression of my changes, we encounter this issue with current version too.

It's related to AdminTab enable/disable performed on enable : https://github.com/PrestaShopCorp/gamification/blob/v2.4.0/gamification.php#L164
and disable :https://github.com/PrestaShopCorp/gamification/blob/v2.4.0/gamification.php#L169

I encounter it since years on my side 😆

**Comment by marwachelly** [comment]
> @marwachelly Hello smiley
> 
> Thanks for your work, your issue on reset / uninstall / disable is not a regression of my changes, we encounter this issue with current version too.
> 
> It's related to AdminTab enable/disable performed on enable : https://github.com/PrestaShopCorp/gamification/blob/v2.4.0/gamification.php#L164 and disable :https://github.com/PrestaShopCorp/gamification/blob/v2.4.0/gamification.php#L169
> 
> I encounter it since years on my side laughing

@Matt75,

Thank you for your feedback and your investigation. But I wasn't able to reproduce the bug with dev branch even with a multilanguage shop. 

https://user-images.githubusercontent.com/89604350/169554941-58515efb-eb7b-4067-a2b0-0f2e2459753a.mp4

Did I miss something to reproduce the bug on a the dev branch ?

Thanks,

**Comment by marwachelly** [comment]
Hello @Matt75,

As discussed in Slack, you reproduced the issue on dev branch with many specific conditions (it depends on multilanguage shop/ permissions ...) So the issue mentioned above don't block your PR. 
PR is QA :heavy_check_mark: 

Thanks,

**Review by marwachelly — APPROVED** [review]
Hello @Matt75,

As discussed in Slack, you reproduced the issue on dev branch with many specific conditions (it depends on multilanguage shop/ permissions ...) So the issue mentioned above don't block your PR. 
PR is QA :heavy_check_mark: 

Thanks,

**Pull request merged**
